apiVersion: v1
kind: Node
metadata:
  name: node-non-evictable
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-non-evictable-1
  namespace: kube-system
  annotations:
    node-balancer/evictable: "false"
spec:
  nodeName: node-non-evictable
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "3"
        memory: "6Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-non-evictable-2
  namespace: default
  annotations:
    node-balancer/evictable: "false"
spec:
  nodeName: node-non-evictable
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "3"
        memory: "6Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-evictable
  namespace: default
  annotations:
    node-balancer/evictable: "true"
spec:
  nodeName: node-non-evictable
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "3Gi" 