apiVersion: v1
kind: Pod
metadata:
  name: test-pod-no-label
  namespace: default
  labels:
    app: test-app-no-label
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-no-label
  namespace: default
  # No validation label - should be ignored by controller
spec:
  selector:
    app: test-app-no-label
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 