apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-handler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-handler-role
rules:
  # Jobs - read, update, delete
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "update", "delete"]
  
  # Pods - read for log collection
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  
  # ConfigMaps - create, update for storing results
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update"]
  
  # Events - create for notifications
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-handler-binding
subjects:
- kind: ServiceAccount
  name: job-handler
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-handler-role
  apiGroup: rbac.authorization.k8s.io 