apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pending
  namespace: default
  labels:
    app: test-app-pending
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "10Gi"  # Request more memory than available
        cpu: "10"       # Request more CPU than available
      limits:
        memory: "20Gi"
        cpu: "20"
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-pending-pod
  namespace: default
  labels:
    service-validator/enabled: "true"
spec:
  selector:
    app: test-app-pending
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 