apiVersion: v1
kind: Service
metadata:
  name: test-service-invalid
  namespace: default
  labels:
    service-validator/enabled: "true"
spec:
  selector:
    app: non-existent-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 