apiVersion: v1
kind: Pod
metadata:
  name: test-pod-valid
  namespace: default
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-valid
  namespace: default
  labels:
    service-validator/enabled: "true"
spec:
  selector:
    app: test-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 