apiVersion: v1
kind: Node
metadata:
  name: node-no-label-1
  labels:
    kubernetes.io/hostname: node-no-label-1
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Node
metadata:
  name: node-no-label-2
  labels:
    kubernetes.io/hostname: node-no-label-2
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-no-label-1
  namespace: default
spec:
  nodeName: node-no-label-1
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "3"
        memory: "6Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-no-label-2
  namespace: default
spec:
  nodeName: node-no-label-2
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "0.5"
        memory: "0.5Gi"
      limits:
        cpu: "1"
        memory: "1Gi" 