apiVersion: v1
kind: Node
metadata:
  name: node-overloaded
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Node
metadata:
  name: node-underutilized
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-overloaded-1
  namespace: default
spec:
  nodeName: node-overloaded
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "2"
        memory: "3Gi"
      limits:
        cpu: "3"
        memory: "4Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-overloaded-2
  namespace: default
spec:
  nodeName: node-overloaded
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "3Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-underutilized
  namespace: default
spec:
  nodeName: node-underutilized
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "0.5"
        memory: "0.5Gi"
      limits:
        cpu: "1"
        memory: "1Gi" 