apiVersion: v1
kind: Node
metadata:
  name: node-balanced-1
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Node
metadata:
  name: node-balanced-2
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-balanced-1
  namespace: default
spec:
  nodeName: node-balanced-1
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-balanced-2
  namespace: default
spec:
  nodeName: node-balanced-2
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi" 