apiVersion: v1
kind: Node
metadata:
  name: node-pdb-protected
  labels:
    node-balancer/enabled: "true"
spec:
  unschedulable: false
status:
  capacity:
    cpu: "4"
    memory: "8Gi"
  allocatable:
    cpu: "4"
    memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pdb-1
  namespace: default
  labels:
    app: pdb-protected-app
spec:
  nodeName: node-pdb-protected
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "3"
        memory: "6Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-pdb-2
  namespace: default
  labels:
    app: pdb-protected-app
spec:
  nodeName: node-pdb-protected
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "3"
        memory: "6Gi"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-protected-app
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pdb-protected-app
status:
  currentHealthy: 2
  desiredHealthy: 2
  disruptionsAllowed: 0
  expectedPods: 2
  observedGeneration: 1 