apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-scaler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-scaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-scaler-binding
subjects:
- kind: ServiceAccount
  name: auto-scaler
  namespace: default
roleRef:
  kind: ClusterRole
  name: auto-scaler-role
  apiGroup: rbac.authorization.k8s.io