apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-syncer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-syncer-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-syncer-binding
subjects:
- kind: ServiceAccount
  name: config-syncer
  namespace: default
roleRef:
  kind: ClusterRole
  name: config-syncer-role
  apiGroup: rbac.authorization.k8s.io 