apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-rotator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-rotator-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-rotator-binding
subjects:
- kind: ServiceAccount
  name: secret-rotator
  namespace: default
roleRef:
  kind: ClusterRole
  name: secret-rotator-role
  apiGroup: rbac.authorization.k8s.io 