# Test Secret that needs rotation (old secret)
apiVersion: v1
kind: Secret
metadata:
  name: old-database-secret
  namespace: default
  labels:
    secret-rotator/enabled: "true"
  annotations:
    secret-rotator/rotation-threshold-days: "30"
    secret-rotator/test-age-days: "45"  # Test: 45 days old
type: Opaque
data:
  username: dGVzdHVzZXI=  # testuser
  password: cGFzc3dvcmQ=  # password
  host: bG9jYWxob3N0  # localhost
---
# Test Secret within rotation threshold (new secret)
apiVersion: v1
kind: Secret
metadata:
  name: new-api-secret
  namespace: default
  labels:
    secret-rotator/enabled: "true"
  annotations:
    secret-rotator/rotation-threshold-days: "90"
    secret-rotator/test-age-days: "30"  # Test: 30 days old
type: Opaque
data:
  api-key: dGVzdC1hcGkta2V5  # test-api-key
  api-secret: cGFzc3dvcmQ=  # password
---
# Test Secret with custom rotation threshold
apiVersion: v1
kind: Secret
metadata:
  name: custom-threshold-secret
  namespace: default
  labels:
    secret-rotator/enabled: "true"
  annotations:
    secret-rotator/rotation-threshold-days: "7"
    secret-rotator/test-age-days: "10"  # Test: 10 days old
type: Opaque
data:
  jwt-secret: anN3dHNlY3JldA==  # jwtsecret
  refresh-token: cmVmcmVzaHRva2Vu  # refreshtoken
---
# Test Secret without rotation label (should be ignored)
apiVersion: v1
kind: Secret
metadata:
  name: ignored-secret
  namespace: default
  # No secret-rotator/enabled label
  annotations:
    secret-rotator/test-age-days: "45"  # Test: 45 days old (but will be ignored)
type: Opaque
data:
  ignored-key: aWdub3JlZGtleQ==  # ignoredkey
---
# Test Secret that was previously marked for rotation but is now within threshold
apiVersion: v1
kind: Secret
metadata:
  name: recovered-secret
  namespace: default
  labels:
    secret-rotator/enabled: "true"
  annotations:
    secret-rotator/rotation-threshold-days: "60"
    secret-rotator/test-age-days: "30"  # Test: 30 days old
    secret-rotator/needs-rotation: "true"  # Previously marked
    secret-rotator/last-check: "2024-03-01T10:00:00Z"
type: Opaque
data:
  recovered-key: cmVjb3ZlcmVka2V5  # recoveredkey